import fetch from 'node-fetch';

let handler = async (m, { conn }) => {
    let message = m.quoted ? m.quoted : m;
    let text = (message.text || '').trim();

    if (!text) {
        throw "✳️ Please provide text for the AI to process.";
    }

    await m.react('⏳'); 

    try {
        
        let response = await fetch(`https://bk9.fun/ai/Text2Img?q=${encodeURIComponent(text)}`);
        let BK8 = await response.json();

       
        if (!BK8.BK9) {
            throw "❌ No image generated by AI.";
        }

       
        await m.react('✅');

       
        let imgUrl = BK8.BK9;
        await conn.sendFile(m.chat, imgUrl, '', 'AI-generated image from text', m, 0, {
            thumbnail: await (await fetch(imgUrl)).buffer()
        });

    } catch (error) {
        await m.react('❌'); 
        throw `❌ error: ${error.message || error}`;
    }
};

handler.help = ['dalle'];
handler.tags = ['ai'];
handler.command = /^(dalle)$/i;

export default handler;
